apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  APPDYNAMICS_AGENT_APPLICATION_NAME: "app"
  APPDYNAMICS_AGENT_ACCOUNT_NAME: "customer1"
  APPDYNAMICS_CONTROLLER_HOST_NAME: "controller-2072nosshco-eayo0b4a.appd-sales.com"
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
  APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
  APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "node"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appd-agent-secret
              key: access-key
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: hello
        - name: JAVA_TOOL_OPTIONS
          value: '-javaagent:/opt/appdynamics-java/javaagent.jar'
        envFrom:
        - configMapRef:
            name: hello-config
        image: cameronmartin/hello
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
        volumeMounts:
        - mountPath: /opt/appdynamics-java
          name: appd-agent-repo
      initContainers:
      - command:
        - cp
        - -ra
        - /opt/appdynamics/.
        - /opt/temp
        image: docker.io/appdynamics/java-agent:20.6.0
        name: appd-agent-attach
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo
      volumes:
        - name: appd-agent-repo
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
